color0 #464653
color1 #ffb4ab
color2 #bfc1ff
color3 #c1c3f3
color4 #f0b0ff
color5 #bfc1ff
color6 #c1c3f3
color7 #e4e1eb
color8 #908f9e
color9 #ffb4ab
color10 #bfc1ff
color11 #c1c3f3
color12 #f0b0ff
color13 #bfc1ff
color14 #c1c3f3
color15 #e4e1eb

cursor                #e4e1eb
cursor_text_color     #131319
background            #131319
foreground            #e4e1eb
selection_foreground  #c7c5d5
selection_background  #464653
active_border_color   #bfc1ff
inactive_border_color #464653
url_color             #bfc1ff

active_tab_foreground   #191c8e
active_tab_background   #bfc1ff
inactive_tab_foreground #c7c5d5
inactive_tab_background #464653
cursor_trail_color      #c7c5d5
