#? Config file for btop v. 1.3+

#* Name of a theme, "Default" or "tty" for terminal colors
color_theme = "Default"

#* If the theme should have a background, False to use terminal background transparency
theme_background = False

#* Sets if 24-bit 'truecolor' should be enabled
truecolor = True

#* Set to True to enable "rounded" box corners
rounded_corners = True

#* Default symbols to use for graph creation, "braille", "block" or "tty".
graph_symbol = "braille"

#* Manually set which boxes to show. Available values are "cpu mem net proc" and "gpu0" through "gpu5"
shown_boxes = "cpu mem net proc"

#* Update time in milliseconds, Recommended minimum 500 ms.
update_ms = 1500

#* Processes sorting, "pid" "program" "arguments" "threads" "user" "memory" "cpu lazy" "cpu responsive"
proc_sorting = "cpu lazy"

#* Reverse sorting order, True or False.
proc_reversed = False

#* Show tree view by default in processes box.
proc_tree = False

#* Show cpu model name in cpu box.
show_cpu_freq = True

#* Draw a clock at top of screen
draw_clock = "%X"
